version: '3.8'

services:
  # Development environment
  app-dev:
    build:
      context: .
      target: build
    ports:
      - "192.168.44.194:3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

  # Production environment
  app-prod:
    build:
      context: .
    ports:
      - "192.168.44.194:3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  node_modules: