version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
      - "3000:3000"
    restart: unless-stopped
    networks:
      - portfolio-network
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3


