version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: portfolio-web
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 256M

networks:
  portfolio-network:
    driver: bridge

volumes:
  node_modules:
